name: Build and Deploy joyeriaPremium

on:
  push:
    branches:
      - main
    paths:
      - 'JoyeriaPremiun/**'
      - '.github/workflows/main.yml'

  workflow_dispatch:

env:
  VERSION_DOTNET: '9'
  AZURE_APP_SERVICE_NOMBRE: Jpremium
  AZURE_APP_SERVICE_UBICACION_PAQUETE: '.'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    env:
      proyecto: JoyeriaPremiun/JoyeriaPremiun.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: ${{ env.VERSION_DOTNET }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.proyecto }}

      - name: Build
        run: dotnet build ${{ env.proyecto }} --no-restore

      - name: Publicar el Web API
        run: dotnet publish ${{ env.proyecto }} -c Release -o miapp --runtime win-x86

      - name: Cargar artefactos
        uses: actions/upload-artifact@v4.6.0
        with:
          path: ./miapp
          name: build

  despliegue:
    name: Despliegue en Azure
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Obtener los artefactos
        uses: actions/download-artifact@v4.1.8
        with:
          name: build

      - name: Despliegue al Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NOMBRE }}
          publish-profile: ${{ secrets.AZURE_PERFIL_PUBLICO }}
          package: ${{ env.AZURE_APP_SERVICE_UBICACION_PAQUETE }}

      
